<?php

declare(strict_types=1);

use function Soinsync\Reports\escape as e;
use function Soinsync\Reports\format_money as money;
use function Soinsync\Reports\format_date as fdate;

/** @var array<string,mixed> $lease    Required (has tenant, unit, property, monthlyRent) */
/** @var array<string,mixed> $period   Required ({month: "YYYY-MM", label, dueDate?}) */
/** @var array<string,mixed>|null $organization */

$lease    = $lease ?? [];
$period   = $period ?? [];
$tenant   = $lease['tenant'] ?? null;
$unit     = $lease['unit'] ?? null;
$property = $lease['property'] ?? null;
$org      = $organization ?? ['name' => 'Soinsync Real Estate'];
$currency = (string) ($currency ?? '');

$amountDue = $period['amount'] ?? $lease['monthlyRent'] ?? 0;
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Invoice <?= e((string) ($period['month'] ?? '')) ?></title>
<style><?php include __DIR__ . '/_layout.tpl.php'; ?></style>
</head>
<body>
<div class="page">
  <div class="header row">
    <div>
      <div class="brand"><?= e($org['name'] ?? 'Soinsync Real Estate') ?></div>
      <?php if (!empty($org['address'])): ?>
        <div class="brand-sub"><?= e($org['address']) ?></div>
      <?php endif; ?>
    </div>
    <div class="right">
      <h1>Rent invoice</h1>
      <div class="muted"><?= e($period['label'] ?? $period['month'] ?? '—') ?></div>
      <div class="muted">Issued <?= e(fdate(date('c'))) ?></div>
    </div>
  </div>

  <table class="meta-table">
    <tr>
      <td class="label">Billed to</td>
      <td><?= e($tenant['fullName'] ?? '—') ?><br>
        <span class="muted"><?= e($tenant['email'] ?? '') ?></span>
      </td>
      <td class="label">Due</td>
      <td><?= e(fdate((string) ($period['dueDate'] ?? ''))) ?></td>
    </tr>
    <tr>
      <td class="label">Property</td>
      <td><?= e($property['name'] ?? '—') ?>
        <?php if (!empty($property['location'])): ?>
          <br><span class="muted"><?= e($property['location']) ?></span>
        <?php endif; ?>
      </td>
      <td class="label">Unit</td>
      <td><?= e($unit['label'] ?? '—') ?></td>
    </tr>
    <tr>
      <td class="label">Lease</td>
      <td>#<?= e($lease['id'] ?? '—') ?></td>
      <td class="label">Period</td>
      <td><?= e($period['label'] ?? $period['month'] ?? '—') ?></td>
    </tr>
  </table>

  <h2>Charges</h2>
  <table class="lined">
    <thead>
      <tr>
        <th>Description</th>
        <th class="right">Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Monthly rent — <?= e($period['label'] ?? $period['month'] ?? '') ?></td>
        <td class="right"><?= e(money($amountDue, $currency)) ?></td>
      </tr>
      <?php foreach (($period['lineItems'] ?? []) as $line): ?>
        <tr>
          <td><?= e($line['label'] ?? '') ?></td>
          <td class="right"><?= e(money($line['amount'] ?? 0, $currency)) ?></td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>

  <div class="total-box">
    <?php if (!empty($period['priorBalance'])): ?>
      <div class="total-row">
        <div>Prior balance</div>
        <div><?= e(money($period['priorBalance'], $currency)) ?></div>
      </div>
    <?php endif; ?>
    <div class="total-row grand">
      <div>Total due</div>
      <div><?= e(money(($period['totalDue'] ?? $amountDue), $currency)) ?></div>
    </div>
  </div>

  <?php if (!empty($period['paymentInstructions'])): ?>
    <div class="section">
      <h2>Payment instructions</h2>
      <div class="muted"><?= nl2br(e($period['paymentInstructions'])) ?></div>
    </div>
  <?php endif; ?>

  <div class="footer">
    Generated by <?= e($org['name'] ?? 'Soinsync Real Estate') ?>.
  </div>
</div>
</body>
</html>
