<?php

declare(strict_types=1);

use function Soinsync\Reports\escape as e;
use function Soinsync\Reports\format_money as money;
use function Soinsync\Reports\format_date as fdate;

/** @var array<string,mixed> $lease     Required (id, status, startDate, endDate?, monthlyRent, tenant, unit, property) */
/** @var array<string,mixed>|null $organization */
/** @var list<string>|null $terms */

$lease    = $lease ?? [];
$tenant   = $lease['tenant'] ?? null;
$unit     = $lease['unit'] ?? null;
$property = $lease['property'] ?? null;
$org      = $organization ?? ['name' => 'Soinsync Real Estate'];
$currency = (string) ($currency ?? '');
$terms    = $terms ?? [
    'Rent is payable monthly on or before the agreed due date.',
    'The tenant agrees to keep the unit in good condition and report damages promptly.',
    'Either party may terminate this agreement subject to the notice period agreed in writing.',
    'The landlord retains the right to inspect the unit with reasonable prior notice.',
];
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Lease Agreement #<?= e($lease['id'] ?? '') ?></title>
<style><?php include __DIR__ . '/_layout.tpl.php'; ?></style>
</head>
<body>
<div class="page">
  <div class="header row">
    <div>
      <div class="brand"><?= e($org['name'] ?? 'Soinsync Real Estate') ?></div>
      <?php if (!empty($org['address'])): ?>
        <div class="brand-sub"><?= e($org['address']) ?></div>
      <?php endif; ?>
    </div>
    <div class="right">
      <h1>Tenancy agreement</h1>
      <div class="muted">Lease #<?= e($lease['id'] ?? '—') ?> · <?= e($lease['status'] ?? '—') ?></div>
      <div class="muted">Issued <?= e(fdate(date('c'))) ?></div>
    </div>
  </div>

  <p>
    This tenancy agreement is made between
    <strong><?= e($org['name'] ?? 'Soinsync Real Estate') ?></strong> (the "Landlord")
    and
    <strong><?= e($tenant['fullName'] ?? '—') ?></strong> (the "Tenant"),
    in respect of the property described below.
  </p>

  <h2>Parties</h2>
  <table class="meta-table">
    <tr>
      <td class="label">Tenant</td>
      <td>
        <?= e($tenant['fullName'] ?? '—') ?><br>
        <span class="muted"><?= e($tenant['email'] ?? '') ?></span>
        <?php if (!empty($tenant['phone'])): ?>
          <br><span class="muted"><?= e($tenant['phone']) ?></span>
        <?php endif; ?>
        <?php if (!empty($tenant['nationalId'])): ?>
          <br><span class="muted">ID: <?= e($tenant['nationalId']) ?></span>
        <?php endif; ?>
      </td>
      <td class="label">Landlord</td>
      <td>
        <?= e($org['name'] ?? 'Soinsync Real Estate') ?>
        <?php if (!empty($org['address'])): ?>
          <br><span class="muted"><?= e($org['address']) ?></span>
        <?php endif; ?>
      </td>
    </tr>
  </table>

  <h2>Premises</h2>
  <table class="meta-table">
    <tr>
      <td class="label">Property</td>
      <td><?= e($property['name'] ?? '—') ?>
        <?php if (!empty($property['location'])): ?>
          <br><span class="muted"><?= e($property['location']) ?></span>
        <?php endif; ?>
      </td>
      <td class="label">Unit</td>
      <td><?= e($unit['label'] ?? '—') ?>
        <?php if (!empty($unit['type'])): ?>
          <br><span class="muted"><?= e(str_replace('_', ' ', strtolower((string) $unit['type']))) ?></span>
        <?php endif; ?>
      </td>
    </tr>
  </table>

  <h2>Terms</h2>
  <table class="meta-table">
    <tr>
      <td class="label">Monthly rent</td>
      <td><strong><?= e(money($lease['monthlyRent'] ?? 0, $currency)) ?></strong></td>
      <td class="label">Status</td>
      <td><?= e($lease['status'] ?? '—') ?></td>
    </tr>
    <tr>
      <td class="label">Start date</td>
      <td><?= e(fdate((string) ($lease['startDate'] ?? ''))) ?></td>
      <td class="label">End date</td>
      <td><?= e(fdate((string) ($lease['endDate'] ?? ''))) ?></td>
    </tr>
  </table>

  <h2>Conditions</h2>
  <ol>
    <?php foreach ($terms as $term): ?>
      <li style="margin: 4px 0;"><?= e($term) ?></li>
    <?php endforeach; ?>
  </ol>

  <div class="signatures">
    <div class="row">
      <div class="col-2">
        <div class="signature-line">Tenant signature</div>
        <div class="muted" style="margin-top: 4px;"><?= e($tenant['fullName'] ?? '') ?></div>
      </div>
      <div class="col-2">
        <div class="signature-line">Landlord signature</div>
        <div class="muted" style="margin-top: 4px;"><?= e($org['name'] ?? '') ?></div>
      </div>
    </div>
  </div>

  <div class="footer">
    Generated by <?= e($org['name'] ?? 'Soinsync Real Estate') ?>.
  </div>
</div>
</body>
</html>
