<?php

declare(strict_types=1);

use function Soinsync\Reports\escape as e;
use function Soinsync\Reports\format_money as money;
use function Soinsync\Reports\format_date as fdate;

/** @var array<string,mixed> $payment   Required */
/** @var array<string,mixed>|null $tenant */
/** @var array<string,mixed>|null $lease */
/** @var array<string,mixed>|null $unit */
/** @var array<string,mixed>|null $property */
/** @var array<string,mixed>|null $organization */

$payment   = $payment ?? [];
$tenant    = $tenant ?? null;
$lease     = $lease ?? null;
$unit      = $unit ?? null;
$property  = $property ?? null;
$org       = $organization ?? ['name' => 'Soinsync Real Estate'];
$currency  = (string) ($currency ?? '');

$method = strtoupper((string) ($payment['method'] ?? ''));
$methodLabel = match ($method) {
    'CASH' => 'Cash',
    'BANK' => 'Bank transfer',
    'MPESA' => 'M-Pesa',
    default => $method ?: '—',
};
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Receipt #<?= e($payment['id'] ?? '') ?></title>
<style><?php include __DIR__ . '/_layout.tpl.php'; ?></style>
</head>
<body>
<div class="page">
  <div class="header row">
    <div>
      <div class="brand"><?= e($org['name'] ?? 'Soinsync Real Estate') ?></div>
      <?php if (!empty($org['address'])): ?>
        <div class="brand-sub"><?= e($org['address']) ?></div>
      <?php endif; ?>
    </div>
    <div class="right">
      <h1>Payment receipt</h1>
      <div class="muted">Receipt #<?= e($payment['id'] ?? '—') ?></div>
      <div class="muted">Issued <?= e(fdate(date('c'))) ?></div>
    </div>
  </div>

  <table class="meta-table">
    <tr>
      <td class="label">Paid by</td>
      <td><?= e($tenant['fullName'] ?? '—') ?><br>
        <span class="muted"><?= e($tenant['email'] ?? '') ?></span>
      </td>
      <td class="label">Paid on</td>
      <td><?= e(fdate((string) ($payment['paidAt'] ?? ''))) ?></td>
    </tr>
    <tr>
      <td class="label">Property</td>
      <td><?= e($property['name'] ?? '—') ?>
        <?php if (!empty($property['location'])): ?>
          <br><span class="muted"><?= e($property['location']) ?></span>
        <?php endif; ?>
      </td>
      <td class="label">Unit</td>
      <td><?= e($unit['label'] ?? '—') ?></td>
    </tr>
    <tr>
      <td class="label">Method</td>
      <td><?= e($methodLabel) ?></td>
      <td class="label">Reference</td>
      <td><?= e($payment['reference'] ?? '—') ?></td>
    </tr>
  </table>

  <h2>Payment</h2>
  <table class="lined">
    <thead>
      <tr>
        <th>Description</th>
        <th class="right">Amount</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          Rent payment
          <?php if (!empty($lease['id'])): ?>
            · Lease #<?= e($lease['id']) ?>
          <?php endif; ?>
          <?php if (!empty($payment['note'])): ?>
            <div class="muted" style="margin-top:4px;"><?= e($payment['note']) ?></div>
          <?php endif; ?>
        </td>
        <td class="right"><?= e(money($payment['amount'] ?? 0, $currency)) ?></td>
      </tr>
    </tbody>
  </table>

  <div class="total-box">
    <div class="total-row grand">
      <div>Total paid</div>
      <div><?= e(money($payment['amount'] ?? 0, $currency)) ?></div>
    </div>
  </div>

  <div class="stamp">
    This receipt confirms the amount above was received. Please retain for your records.
  </div>

  <div class="footer">
    Generated by <?= e($org['name'] ?? 'Soinsync Real Estate') ?>. No signature required.
  </div>
</div>
</body>
</html>
