<?php

declare(strict_types=1);

use function Soinsync\Reports\escape as e;

/** @var string $title         Required */
/** @var string|null $subtitle */
/** @var array<string,mixed>|null $organization */
/** @var list<array<string,mixed>>|null $sections
 *      Each section: { heading: string, type: "kv"|"table"|"text",
 *                      rows?: array, columns?: list<string>, body?: string } */

$title    = $title ?? 'Report';
$subtitle = $subtitle ?? null;
$org      = $organization ?? ['name' => 'Soinsync Real Estate'];
$sections = $sections ?? [];
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title><?= e($title) ?></title>
<style><?php include __DIR__ . '/_layout.tpl.php'; ?></style>
</head>
<body>
<div class="page">
  <div class="header row">
    <div>
      <div class="brand"><?= e($org['name'] ?? 'Soinsync Real Estate') ?></div>
      <?php if (!empty($org['address'])): ?>
        <div class="brand-sub"><?= e($org['address']) ?></div>
      <?php endif; ?>
    </div>
    <div class="right">
      <h1><?= e($title) ?></h1>
      <?php if ($subtitle): ?>
        <div class="muted"><?= e($subtitle) ?></div>
      <?php endif; ?>
      <div class="muted">Generated <?= e(date('d M Y H:i')) ?></div>
    </div>
  </div>

  <?php foreach ($sections as $section): ?>
    <?php $type = (string) ($section['type'] ?? 'text'); ?>
    <div class="section">
      <?php if (!empty($section['heading'])): ?>
        <h2><?= e($section['heading']) ?></h2>
      <?php endif; ?>

      <?php if ($type === 'kv' && isset($section['rows']) && is_array($section['rows'])): ?>
        <table class="meta-table">
          <?php foreach ($section['rows'] as $label => $value): ?>
            <tr>
              <td class="label"><?= e($label) ?></td>
              <td><?= e(is_scalar($value) ? (string) $value : json_encode($value)) ?></td>
            </tr>
          <?php endforeach; ?>
        </table>

      <?php elseif ($type === 'table' && isset($section['columns'], $section['rows'])): ?>
        <table class="lined">
          <thead>
            <tr>
              <?php foreach ($section['columns'] as $col): ?>
                <th><?= e($col) ?></th>
              <?php endforeach; ?>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($section['rows'] as $row): ?>
              <tr>
                <?php foreach ($section['columns'] as $col): ?>
                  <td><?= e(is_scalar($row[$col] ?? '') ? (string) ($row[$col] ?? '') : json_encode($row[$col] ?? '')) ?></td>
                <?php endforeach; ?>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>

      <?php elseif ($type === 'text'): ?>
        <div><?= nl2br(e((string) ($section['body'] ?? ''))) ?></div>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>

  <div class="footer">
    Generated by <?= e($org['name'] ?? 'Soinsync Real Estate') ?>.
  </div>
</div>
</body>
</html>
